---
kind: pipeline
type: kubernetes
name: rtp-io-lib

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
  commands:
  - /root/entrypoint.sh
  - git fetch --tags
  - sbt clean test
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: regt-build-bot
  when:
    event:
    - push
    - tag

- name: publish
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
  commands:
  - /root/entrypoint.sh
  - sbt +publish
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_SERVER: https://artifactory.digital.homeoffice.gov.uk/
    ARTIFACTORY_USERNAME: regt-build-bot
  when:
    event:
    - push
    - tag

...
